connection:
  mysql:
    enabled: false
    address: "localhost:3306"
    username: "root"
    passowrd: ""
    database: "test"
  sqlite:
    file: "questions.db"

question:
  inventory:
    title: 'Minhas Dúvidas'
    lines: 6
    item:
      name: '&7ID: &f#@id'
      material: PAPER
      lore: # lore de uma pergunta ainda não respondida
        - ''
        - '&7Dúvida: &f@question'
        - '&7Criada em: &f@createdAt'
        - '&7Situação: &f@situation'
      lore-replied: # linhas que serão adicionadas caso a pergunta tenha sido respondida
        - ''
        - '&7Respondida por: &f@staff'
        - '&7Respondida em: &f@@repliedAt'
        - '&7Resposta: &f@reply'
        - ''
  staff-inventory:
    title: 'Lista de Dúvidas'
    lines: 6
    item:
      name: '&aDúvida de @player'
      material: PAPER
      lore:
        - ''
        - '&7Dúvida: &f@question'
        - '&7Criada em: &f@createdAt'
        - '&7Situação: &f@situation'
      lore-replied:
        - ''
        - '&7Respondida por: &f@staff'
        - '&7Respondida em: &f@@repliedAt'
        - '&7Resposta: &f@reply'
        - ''
  new-question: # Mensagem que será enviada para todos os jogadores que tiverem permissão (astroquestions.staff)
    - ''
    - '&aUm nova dúvida está disponível para ser respondida!'
    - '&aClique aqui para abrir o menu de dúvidas.'
    - ''
  question-replyed:
    - ''
    - '&aSua pergunta &7(#@id) foi respondida por &f@staff&a!'
    - ''
    - '&aResposta:'
    - '&7  @reply'

messages:
  error: '&cOcorreu um erro durante a execução deste comando.'
  no-permission: '&cVocê não tem permissão para utilizar este comando.'
  invalid-target: '&cEste comando apenas pode ser executado por jogadores.'
  invalid-usage: '&cUso incorreto, utilize /duvida <dúvida>'
  already-replied: '&cEsta dúvida já foi respondida.'
  reply-sent: '&aA sua resposta foi enviada com sucesso.'
  text-edited: '&aO texto da pergunta foi editada com sucesso.'
